version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  dashboard:
    build: ./dashboard
    container_name: dashboard
    environment:
      - REACT_APP_CONF_RM_URL=http://localhost/calendar-api/schedule
      - REACT_APP_FOOSBALL_URL=http://localhost/foosball-api
      - REACT_APP_FOOSBALL_WS=ws://localhost/foosball-api
      - REACT_APP_PHOTOS_URL=http://localhost/picture-uploader
      - REACT_APP_MESSAGE_BOARD_API_URL=http://localhost/messages
      - REACT_APP_KUDO_URL=http://localhost/kudos
    volumes:
      - ./dashboard/src/:/app/src/
      - ./dashboard/public/:/app/public/
    command: npm start

  picture-uploader:
    build: ./picture-uploader/
    container_name: picture-uploader
    environment:
      - NODE_ENV=production
      - PIC_API_KEY=pic-api-key
      - STORE_PATH=/var/lib/picture-uploader/uploads
    volumes:
      - photos:/var/lib/picture-uploader/uploads

  calendar-api:
    build: ./calendar-api/
    container_name: calendar-api
    volumes:
      - ./calendar-api/calendar_config.json:/app/calendar_config.json

  foosball-api:
    build: ./foosball-api/
    container_name: foosball-api
    environment:
      - "NODE_ENV=production"
      - "DATABASE_URL=pgsql://test:test@foosdb/foosball"

  foosdb:
    container_name: foosdb
    image: postgres:12
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=foosball"
    ports:
      - 5432:5432


  messages-backend:
    container_name: messages-backend
    build: ./messages-api/
    environment:
      - "NODE_ENV=development"
      - "MESSAGES_HMAC_KEY=development"
      - "PORT=8011"
    depends_on:
      - messages_database

  messages_database:
    container_name: messages_database
    image: postgres:12
    restart: always
    volumes:
      - messages-db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=messages_db"

  kudos-api:
    image: kudos-api
    restart: always
    environment: 
      KUDO_PASSWORD: kudoapi
      JDBC_URL: 'jdbc:mysql://kudos-mysql-db/dashboard?allowPublicKeyRetrieval=true&useSSL=false'
      DB_USERNAME: root
      DB_PASSWORD: kudosapi
    depends_on:
      - kudos-mysql-db

  kudos-mysql-db:
    container_name: kudos-mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kudosapi
    volumes:
      - kudos-db:/var/lib/mysql

volumes:
  db:
  photos:
  messages-db:
  kudos-db: