version: "3.1"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  dashboard:
    # image: registry.gitlab.com/collinear/collinear-dashboard-server-config/dashboard
    container_name: dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ./dashboard/src:/app/src
      - ./dashboard/public:/app/public
    environment:
      - REACT_APP_AUTH_URL=http://localhost/auth
      - REACT_APP_CONF_RM_URL=http://localhost/calendar-api/schedule
      - REACT_APP_FOOSBALL_URL=http://localhost/foosball-api
      - REACT_APP_FOOSBALL_WS=ws://localhost/foosball-api
      - REACT_APP_PHOTOS_URL=http://localhost/picture-uploader
      - REACT_APP_MESSAGE_BOARD_API_URL=http://localhost/messages
      - REACT_APP_KUDO_URL=http://localhost/kudos

  auth-api:
    image: auth-api 
    container_name: auth-api
    restart: always
    environment:
      - "NODE_ENV=production"
      - "AUTH_PASSWORD=$$2b$$10$$Eewkf.tM.vcsNESzn0.SguO7srJD0BXs/9OP3J6x8dGt5fwqfhILu"
      - "AUTH_SECRET=TEST_SECRET"
      - "PORT=8011"
      - "DATABASE_URL=pgsql://dashboard:dashboard@dashboard-db/message_board"

  picture-uploader:
    image: registry.gitlab.com/collinear/collinear-dashboard-server-config/picture-uploader
    container_name: picture-uploader
    environment:
      - NODE_ENV=production
      - PIC_API_KEY=pic-api-key
      - AUTH_SECRET=TEST_SECRET
      - STORE_PATH=/var/lib/picture-uploader/uploads
    volumes:
      - photos:/var/lib/picture-uploader/uploads

  calendar-api:
    image: registry.gitlab.com/collinear/collinear-dashboard-server-config/calendar-api
    container_name: calendar-api
    volumes:
      - ./calendar-api/calendar_config.json:/app/calendar_config.json

  foosball-api:
    image: foosball-api
    container_name: foosball-api
    restart: always
    environment:
      - "NODE_ENV=production"
      - "AUTH_SECRET=TEST_SECRET"
      - "DATABASE_URL=pgsql://dashboard:dashboard@dashboard-db/foosball"

  messages-api:
    image: messages-api
    container_name: messages-api
    restart: always
    environment:
      - "NODE_ENV=production"
      - "MESSAGES_HMAC_KEY=development"
      - "AUTH_SECRET=TEST_SECRET"
      - "PORT=8011"
      - "DATABASE_URL=pgsql://dashboard:dashboard@dashboard-db/message_board"

  kudos-api:
    image: kudos-api
    restart: always
    environment:
      KUDO_PASSWORD: kudoapi
      JDBC_URL: "jdbc:postgresql://dashboard-db/kudos_board"
      DB_USERNAME: dashboard
      DB_PASSWORD: dashboard

volumes:
  photos:
