version: '3'

services:

  backend:
    container_name: backend
    image: node:10.15
    environment:
      - "NODE_ENV=development"
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - database
    ports:
      - 8000:8000
    command: npm install && npm run dev

  frontend:
    container_name: frontend
    image: node:10.15
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm install && npm run start

  database:
    container_name: database
    image: postgres:12
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=foosball"
    ports:
      - 5432:5432

volumes:
  db:
