version: "3"

services:
  messages-backend:
    container_name: messages-backend
    image: node:12
    environment:
      - "NODE_ENV=development"
      - "MESSAGES_HMAC_KEY=development"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - messages_database
    ports:
      - 8011:8000
    command: sh -c "npm install && npm run dev"

  messages_database:
    container_name: messages_database
    image: postgres:12
    restart: always
    volumes:
      - messages-db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=messages_db"

volumes:
  messages-db:
