version: "3"

services:
  kudos-api:
    image: kudos-api
    restart: always
    ports:
      - 8080:8080
    environment: 
      KUDO_PASSWORD: kudoapi
      JDBC_URL: 'jdbc:postgresql://db/kudos_board'
      DB_USERNAME: kudosapi
      DB_PASSWORD: kudosapi
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    restart: always
    volumes:
      - kudos-db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=kudosapi"
      - "POSTGRES_PASSWORD=kudosapi"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  kudos-db:
