version: "3"

services:
  kudos-api:
    image: kudos-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kudosapi
    volumes:
      - kudos-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  kudos-db:
