version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kudosapi
    ports:
      - "3306:3306"
    restart: always
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - mysql